services:
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8108'"]
      interval: 5s
      timeout: 5s
      retries: 5

  amb-relay:
    build:
      context: .
      dockerfile: Dockerfile.relay
    restart: on-failure
    ports:
      - "3334:3334"
    depends_on:
      typesense:
        condition: service_healthy
    environment:
      - NAME=${NAME}
      - PUBKEY=${PUBKEY}
      - DESCRIPTION=${DESCRIPTION}
      - ICON=${ICON}
      - TS_APIKEY=${TS_APIKEY}
      - TS_HOST=http://typesense:8108
      - TS_COLLECTION=${TS_COLLECTION}
      - EMBED_ENDPOINT=${EMBED_ENDPOINT}
      - EMBED_TOKEN=${EMBED_TOKEN}
